### ISSUE TITLE
Unable to create poster using the 7.3 part of the book

### ISSUE THREAD

**Issue by N0rbert** [pzhaonet/bookdownplus-textbook#4]
Thank you for the great package and book!

On my Ubuntu 16.04.6 LTS I have installed R, TexLive, RStudio preview 1.2.1303 and dependencies from https://github.com/exporl/kuleuven-templates#linux :

```
sudo apt-get install make
sudo apt-get install texlive texlive-latex-recommended texlive-science texlive-bibtex-extra imagemagick
sudo apt-get install ghostscript posterazor libreoffice
sudo apt-get install pandoc python-pandocfilters
```

Then I installed `bookdownplus` package with `install.packages('bookdownplus')`.
Afterwards I'm trying to follow the https://bookdown.org/baydap/bookdownplus/academic.html#poster
to create Poster from RMarkdown document.

So I get the following output:

```
> bookdownplus::bookdownplus(template = 'poster', theme = 'eco')
Error in bookdownplus::bookdownplus(template = "poster", theme = "eco") : 
  unused argument (theme = "eco")
> bookdownplus::bookdownplus(template = 'poster')
poster is unavailable. Please check whether your spelling is correct. Run get_template() to see available templates.

```

So I can't create a poster, but you wrote about it in the book, so I expect that it could be created...

It seems that there are no poster-related templates in `~/R`:

```
$ grep -ir poster ~/R
/home/mate/R/x86_64-pc-linux-gnu-library/3.5/bookdownplus/proj/body.Rmd:bookdown for details. Additionally, if you want to produce a poster, phython must be installed before using, and the path of phython might have to be added to the environmental variables for Windows users.
/home/mate/R/x86_64-pc-linux-gnu-library/3.5/bookdownplus/bib/bib.bib:  title =     {postr: Generage posters with r markdown},

```

What happened here? Is book outdated? Did you really removed poster-related code from package?

**Comment by pzhaonet** [comment]
As there are better packages for making posters available, the poster template was removed from bookdownplus due to poor maintenance.  The book is outdated as well. 

I would suggest the pagedown package or drposter package. 

Thank you very much for your attention on bookdownplus.

**Comment by N0rbert** [comment]
OK, thank you.
I'll test the suggested alternatives and maybe [`posterdown`](https://github.com/brentthorne/posterdown) :)
